/*=============================================================================
  NHTSA Fleet Safety & Crashworthiness Intelligence Portal
  03_teardown.sql — Full Environment Cleanup (reverse order)
=============================================================================*/

USE ROLE SYSADMIN;

-- Drop SPCS service
DROP SERVICE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.NHTSA_SERVICE;

-- Drop compute pool
DROP COMPUTE POOL IF EXISTS NHTSA_COMPUTE_POOL;

-- Drop image repository
DROP IMAGE REPOSITORY IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.NHTSA_REPO;

-- Drop views
DROP VIEW IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_BIOMECHANICAL_RISK;
DROP VIEW IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_ADVANCED_SAFETY_TECH_ADOPTION;
DROP VIEW IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_SAFETY_SUMMARY_BY_MAKE;

-- Drop table
DROP TABLE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.RAW_SAFERCAR;

-- Drop stage and file format
DROP STAGE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.RAW_STAGE;
DROP FILE FORMAT IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.CSV_SAFERCAR;

-- Drop schema and database
DROP SCHEMA IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA;
DROP DATABASE IF EXISTS NHTSA_SAFECAR_DEMO;

-- Drop service role
DROP ROLE IF EXISTS NHTSA_SERVICE_ROLE;

-- Drop warehouse
DROP WAREHOUSE IF EXISTS NHTSA_WH;
