-- ============================================================================
-- NHTSA SafeCar Demo — Analytical Views
-- ============================================================================

USE DATABASE NHTSA_SAFECAR_DEMO;
USE SCHEMA SAFETY_DATA;

-- Safety summary aggregated by make and model year
CREATE OR REPLACE VIEW V_SAFETY_SUMMARY_BY_MAKE AS
SELECT
    MAKE,
    MODEL_YR,
    COUNT(*) AS VEHICLE_COUNT,
    ROUND(AVG(TRY_TO_NUMBER(OVERALL_STARS)), 2) AS AVG_OVERALL_STARS,
    ROUND(AVG(TRY_TO_NUMBER(OVERALL_FRNT_STARS)), 2) AS AVG_FRONTAL_STARS,
    ROUND(AVG(TRY_TO_NUMBER(OVERALL_SIDE_STARS)), 2) AS AVG_SIDE_STARS,
    ROUND(AVG(TRY_TO_NUMBER(ROLLOVER_STARS)), 2) AS AVG_ROLLOVER_STARS,
    ROUND(AVG(TRY_TO_NUMBER(FRNT_DRIV_STARS)), 2) AS AVG_FRNT_DRIV_STARS,
    ROUND(AVG(TRY_TO_NUMBER(FRNT_PASS_STARS)), 2) AS AVG_FRNT_PASS_STARS
FROM RAW_SAFERCAR
WHERE MAKE IS NOT NULL
GROUP BY MAKE, MODEL_YR
ORDER BY MAKE, MODEL_YR;

-- ADAS technology adoption percentages by year and body style
CREATE OR REPLACE VIEW V_ADVANCED_SAFETY_TECH_ADOPTION AS
SELECT
    MODEL_YR,
    BODY_STYLE,
    COUNT(*) AS VEHICLE_COUNT,
    ROUND(100.0 * COUNT_IF(FRNT_COLLISION_WARNING IS NOT NULL AND TRIM(FRNT_COLLISION_WARNING) != '')
        / NULLIF(COUNT(*), 0), 1) AS PCT_FCW,
    ROUND(100.0 * COUNT_IF(CRASH_IMMINENT_BRAKE IS NOT NULL AND TRIM(CRASH_IMMINENT_BRAKE) != '')
        / NULLIF(COUNT(*), 0), 1) AS PCT_CIB,
    ROUND(100.0 * COUNT_IF(LANE_DEPARTURE_WARNING IS NOT NULL AND TRIM(LANE_DEPARTURE_WARNING) != '')
        / NULLIF(COUNT(*), 0), 1) AS PCT_LDW,
    ROUND(100.0 * COUNT_IF(ADAPTIVE_CRUISE_CONTROL IS NOT NULL AND TRIM(ADAPTIVE_CRUISE_CONTROL) != '')
        / NULLIF(COUNT(*), 0), 1) AS PCT_ACC,
    ROUND(100.0 * COUNT_IF(BLIND_SPOT_DETECTION IS NOT NULL AND TRIM(BLIND_SPOT_DETECTION) != '')
        / NULLIF(COUNT(*), 0), 1) AS PCT_BLIND_SPOT,
    ROUND(100.0 * COUNT_IF(DYNAMIC_BRAKE_SUPPORT IS NOT NULL AND TRIM(DYNAMIC_BRAKE_SUPPORT) != '')
        / NULLIF(COUNT(*), 0), 1) AS PCT_DBS
FROM RAW_SAFERCAR
WHERE MODEL_YR IS NOT NULL AND BODY_STYLE IS NOT NULL
GROUP BY MODEL_YR, BODY_STYLE
ORDER BY MODEL_YR, BODY_STYLE;

-- Biomechanical risk factors: weight, stability, crash test injury metrics
CREATE OR REPLACE VIEW V_BIOMECHANICAL_RISK AS
SELECT
    MAKE,
    MODEL,
    MODEL_YR,
    BODY_STYLE,
    DRIVE_TRAIN,
    TRY_TO_NUMBER(CURB_WEIGHT) AS CURB_WEIGHT_LBS,
    STATIC_STABI_FACTOR,
    ROLLOVER_POSSIBILITY,
    TRY_TO_NUMBER(ROLLOVER_STARS) AS ROLLOVER_STAR_RATING,
    HIC15_DRIV,
    CHEST_DEFL_DRIV,
    SIDE_HIC_36_DRIV,
    RIB_DEFLECTION_DRIV,
    SYMPHYSIS_FORCE_DRIV,
    PELVIC_FORCE_PASS
FROM RAW_SAFERCAR
WHERE TRY_TO_NUMBER(CURB_WEIGHT) IS NOT NULL
  AND (HIC15_DRIV IS NOT NULL OR STATIC_STABI_FACTOR IS NOT NULL)
ORDER BY MAKE, MODEL, MODEL_YR;

-- Searchable safety notes for Cortex Search indexing
CREATE OR REPLACE VIEW V_SAFETY_NOTES_SEARCHABLE AS
SELECT
    MAKE || ' ' || MODEL || ' ' || COALESCE(TO_CHAR(MODEL_YR), '') AS VEHICLE_ID,
    MAKE,
    MODEL,
    MODEL_YR,
    BODY_STYLE,
    COALESCE(FRNT_FOOT_NOTES, '') || ' ' ||
    COALESCE(FRNT_FOOT_NOTES_PASS, '') || ' ' ||
    COALESCE(FRNT_SAFETY_CONCERN_DRIV, '') || ' ' ||
    COALESCE(FRNT_SAFETY_CONCERN_PASS, '') || ' ' ||
    COALESCE(SIDE_FOOT_NOTES, '') || ' ' ||
    COALESCE(SIDE_FOOT_NOTES_PASS, '') || ' ' ||
    COALESCE(SIDE_SAFETY_CONCERN_DRIV, '') || ' ' ||
    COALESCE(SIDE_SAFETY_CONCERN_PASS, '') || ' ' ||
    COALESCE(POLE_FOOT_NOTES, '') || ' ' ||
    COALESCE(POLE_SAFETY_CONCERN, '') || ' ' ||
    COALESCE(ROLL_FOOT_NOTES, '') || ' ' ||
    COALESCE(ROLL_SAFETY_CONCERN, '') AS COMBINED_SAFETY_NOTES
FROM RAW_SAFERCAR
WHERE FRNT_FOOT_NOTES IS NOT NULL
   OR SIDE_FOOT_NOTES IS NOT NULL
   OR POLE_FOOT_NOTES IS NOT NULL
   OR POLE_SAFETY_CONCERN IS NOT NULL
   OR ROLL_SAFETY_CONCERN IS NOT NULL
   OR FRNT_SAFETY_CONCERN_DRIV IS NOT NULL
   OR SIDE_SAFETY_CONCERN_DRIV IS NOT NULL;
