-- ============================================================================
-- NHTSA SafeCar Demo — Step 4: Create Stored Procedures
-- ============================================================================

USE WAREHOUSE NHTSA_SAFECAR_WH;
USE SCHEMA NHTSA_SAFECAR_DEMO.SAFETY_DATA;

-- ADAS technology adoption lookup
CREATE OR REPLACE PROCEDURE SP_ADAS_TECH_ADOPTION(
    P_MODEL_YR_START NUMBER(38,0) DEFAULT NULL,
    P_MODEL_YR_END NUMBER(38,0) DEFAULT NULL,
    P_BODY_STYLE VARCHAR DEFAULT NULL,
    P_LIMIT NUMBER(38,0) DEFAULT 50
)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS
'BEGIN
    LET rs RESULTSET := (
        SELECT
            MODEL_YR,
            BODY_STYLE,
            VEHICLE_COUNT,
            PCT_FCW AS PCT_FORWARD_COLLISION_WARNING,
            PCT_CIB AS PCT_CRASH_IMMINENT_BRAKING,
            PCT_LDW AS PCT_LANE_DEPARTURE_WARNING,
            PCT_ACC AS PCT_ADAPTIVE_CRUISE_CONTROL,
            PCT_BLIND_SPOT AS PCT_BLIND_SPOT_DETECTION,
            PCT_DBS AS PCT_DYNAMIC_BRAKE_SUPPORT
        FROM NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_ADVANCED_SAFETY_TECH_ADOPTION
        WHERE (:P_MODEL_YR_START IS NULL OR MODEL_YR >= :P_MODEL_YR_START)
          AND (:P_MODEL_YR_END IS NULL OR MODEL_YR <= :P_MODEL_YR_END)
          AND (:P_BODY_STYLE IS NULL OR UPPER(BODY_STYLE) LIKE ''%'' || UPPER(:P_BODY_STYLE) || ''%'')
        ORDER BY MODEL_YR DESC, BODY_STYLE
        LIMIT :P_LIMIT
    );
    RETURN TABLE(rs);
END';

-- Biomechanical risk lookup
CREATE OR REPLACE PROCEDURE SP_BIOMECHANICAL_RISK(
    P_MAKE VARCHAR DEFAULT NULL,
    P_MODEL VARCHAR DEFAULT NULL,
    P_MODEL_YR NUMBER(38,0) DEFAULT NULL,
    P_BODY_STYLE VARCHAR DEFAULT NULL,
    P_LIMIT NUMBER(38,0) DEFAULT 25
)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS
'BEGIN
    LET rs RESULTSET := (
        SELECT
            MAKE,
            MODEL,
            MODEL_YR,
            BODY_STYLE,
            DRIVE_TRAIN,
            CURB_WEIGHT_LBS,
            STATIC_STABI_FACTOR,
            ROLLOVER_POSSIBILITY,
            ROLLOVER_STAR_RATING,
            HIC15_DRIV AS HEAD_INJURY_CRITERION_DRIVER,
            CHEST_DEFL_DRIV AS CHEST_DEFLECTION_DRIVER,
            SIDE_HIC_36_DRIV AS SIDE_HEAD_INJURY_DRIVER,
            RIB_DEFLECTION_DRIV AS RIB_DEFLECTION_DRIVER,
            SYMPHYSIS_FORCE_DRIV AS PELVIS_FORCE_DRIVER,
            PELVIC_FORCE_PASS AS PELVIS_FORCE_PASSENGER
        FROM NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_BIOMECHANICAL_RISK
        WHERE (:P_MAKE IS NULL OR UPPER(MAKE) LIKE ''%'' || UPPER(:P_MAKE) || ''%'')
          AND (:P_MODEL IS NULL OR UPPER(MODEL) LIKE ''%'' || UPPER(:P_MODEL) || ''%'')
          AND (:P_MODEL_YR IS NULL OR MODEL_YR = :P_MODEL_YR)
          AND (:P_BODY_STYLE IS NULL OR UPPER(BODY_STYLE) LIKE ''%'' || UPPER(:P_BODY_STYLE) || ''%'')
        ORDER BY ROLLOVER_POSSIBILITY DESC NULLS LAST, MODEL_YR DESC
        LIMIT :P_LIMIT
    );
    RETURN TABLE(rs);
END';

-- Safety ratings lookup
CREATE OR REPLACE PROCEDURE SP_SAFETY_RATINGS_LOOKUP(
    P_MAKE VARCHAR DEFAULT NULL,
    P_MODEL VARCHAR DEFAULT NULL,
    P_MODEL_YR NUMBER(38,0) DEFAULT NULL,
    P_BODY_STYLE VARCHAR DEFAULT NULL,
    P_LIMIT NUMBER(38,0) DEFAULT 25
)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS
'BEGIN
    LET rs RESULTSET := (
        SELECT
            MAKE,
            MODEL,
            MODEL_YR,
            BODY_STYLE,
            OVERALL_STARS,
            OVERALL_FRNT_STARS AS FRONTAL_STARS,
            OVERALL_SIDE_STARS AS SIDE_STARS,
            ROLLOVER_STARS,
            FRNT_DRIV_STARS,
            FRNT_PASS_STARS,
            SIDE_DRIV_STARS,
            SIDE_PASS_STARS,
            SIDE_POLE_STARS
        FROM NHTSA_SAFECAR_DEMO.SAFETY_DATA.RAW_SAFERCAR
        WHERE (:P_MAKE IS NULL OR UPPER(MAKE) LIKE ''%'' || UPPER(:P_MAKE) || ''%'')
          AND (:P_MODEL IS NULL OR UPPER(MODEL) LIKE ''%'' || UPPER(:P_MODEL) || ''%'')
          AND (:P_MODEL_YR IS NULL OR MODEL_YR = :P_MODEL_YR)
          AND (:P_BODY_STYLE IS NULL OR UPPER(BODY_STYLE) LIKE ''%'' || UPPER(:P_BODY_STYLE) || ''%'')
        ORDER BY MODEL_YR DESC, MAKE, MODEL
        LIMIT :P_LIMIT
    );
    RETURN TABLE(rs);
END';

-- Safety summary by make
CREATE OR REPLACE PROCEDURE SP_SAFETY_SUMMARY_BY_MAKE(
    P_MAKE VARCHAR DEFAULT NULL,
    P_MODEL_YR_START NUMBER(38,0) DEFAULT NULL,
    P_MODEL_YR_END NUMBER(38,0) DEFAULT NULL,
    P_LIMIT NUMBER(38,0) DEFAULT 50
)
RETURNS TABLE ()
LANGUAGE SQL
EXECUTE AS OWNER
AS
'BEGIN
    LET rs RESULTSET := (
        SELECT
            MAKE,
            MODEL_YR,
            VEHICLE_COUNT,
            AVG_OVERALL_STARS,
            AVG_FRONTAL_STARS,
            AVG_SIDE_STARS,
            AVG_ROLLOVER_STARS,
            AVG_FRNT_DRIV_STARS,
            AVG_FRNT_PASS_STARS
        FROM NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_SAFETY_SUMMARY_BY_MAKE
        WHERE (:P_MAKE IS NULL OR UPPER(MAKE) LIKE ''%'' || UPPER(:P_MAKE) || ''%'')
          AND (:P_MODEL_YR_START IS NULL OR MODEL_YR >= :P_MODEL_YR_START)
          AND (:P_MODEL_YR_END IS NULL OR MODEL_YR <= :P_MODEL_YR_END)
        ORDER BY MAKE, MODEL_YR DESC
        LIMIT :P_LIMIT
    );
    RETURN TABLE(rs);
END';
