-- ============================================================================
-- NHTSA SafeCar Demo — Teardown (removes everything)
-- ============================================================================
-- Run this script to completely remove all demo objects from your account.
-- This is safe to run even if some objects don't exist.
-- ============================================================================

USE ROLE SYSADMIN;

-- Streamlit app
DROP STREAMLIT IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.NHTSA_SAFECAR_ANALYTICS;

-- Cortex Search service
DROP CORTEX SEARCH SERVICE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.NHTSA_SAFETY_NOTES_INDEX;

-- Semantic view
DROP SEMANTIC VIEW IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.SAFECAR_SAFETY_RATINGS;

-- Stored procedures
DROP PROCEDURE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.SP_ADAS_TECH_ADOPTION(NUMBER, NUMBER, VARCHAR, NUMBER);
DROP PROCEDURE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.SP_BIOMECHANICAL_RISK(VARCHAR, VARCHAR, NUMBER, VARCHAR, NUMBER);
DROP PROCEDURE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.SP_SAFETY_RATINGS_LOOKUP(VARCHAR, VARCHAR, NUMBER, VARCHAR, NUMBER);
DROP PROCEDURE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.SP_SAFETY_SUMMARY_BY_MAKE(VARCHAR, NUMBER, NUMBER, NUMBER);

-- Views
DROP VIEW IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_SAFETY_NOTES_SEARCHABLE;
DROP VIEW IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_BIOMECHANICAL_RISK;
DROP VIEW IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_ADVANCED_SAFETY_TECH_ADOPTION;
DROP VIEW IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.V_SAFETY_SUMMARY_BY_MAKE;

-- Table
DROP TABLE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.RAW_SAFERCAR;

-- Stage and file format
DROP STAGE IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.RAW_STAGE;
DROP FILE FORMAT IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA.CSV_SAFERCAR;

-- Schema and database
DROP SCHEMA IF EXISTS NHTSA_SAFECAR_DEMO.SAFETY_DATA;
DROP DATABASE IF EXISTS NHTSA_SAFECAR_DEMO;

-- Warehouse
DROP WAREHOUSE IF EXISTS NHTSA_SAFECAR_WH;
